---
- name: Installing NTP APT package
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - ntp
  when: ansible_os_family == 'Debian'


- name: Installing yum ntp package
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - ntp
  when: ansible_os_family == 'RedHat'
