---
  - include: install.yml
  
  - name: Load the variables
    include_vars: '{{ ansible_os_family }}.yml'

  - name: Copy the ntp.conf Jinja2 template file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
    - restart ntp

  - name: init.d changes Enabling the service
    service: name='{{ ntpd }}' state=started enabled=yes pattern='/ntp' 

  - name: View the NTP Settings 
    command: cat /etc/ntp.conf
    register: out
  
  - debug: var=out.stdout_lines

  - name: ntpq Output
    command: ntpq -p
    register: out

  - debug: var=out.stdout_lines
