# To Run this Playbook Issue the command
# ansible-playbook nmap.yml
# Author Anish Nath
#https://goo.gl/W4rtXg

---
- hosts: localhost
  become: yes
  gather_facts: false
  roles:
    - { role: nmap }
